import { FC } from 'react';
import { useTranslation } from 'react-i18next';

import TableRow from '../TableRow';

import s from './Table.module.scss';

interface TableProps {}
const inventory = [
  {
    name: "FIREWIRE FRK 6'2'' SURFBOARD SURFBOARD",
    id: '001',
    availability: 'Booked',
    price: 15,
    registered: '2024-04-18',
    action: false,
    groupNumber: 2,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },

  {
    name: 'Item 2',
    id: '002',
    availability: 'Booked',
    price: 15,
    registered: '2024-04-18',
    action: false,
    groupNumber: 2,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 3',
    id: '003',
    availability: 'Available',
    price: 20,
    registered: '2024-04-22',
    action: true,
    groupNumber: 1,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 4',
    id: '004',
    availability: 'Booked',
    price: 25,
    registered: '2024-04-16',
    action: false,
    groupNumber: 3,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 5',
    id: '005',
    availability: 'Available',
    price: 30,
    registered: '2024-04-19',
    action: true,
    groupNumber: 2,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 6',
    id: '006',
    availability: 'Service',
    price: 35,
    registered: '2024-04-21',
    action: false,
    groupNumber: 2,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 7',
    id: '007',
    availability: 'Service',
    price: 40,
    registered: '2024-04-23',
    action: true,
    groupNumber: 2,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 8',
    id: '008',
    availability: 'Booked',
    price: 45,
    registered: '2024-04-17',
    action: false,
    groupNumber: 1,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 9',
    id: '009',
    availability: 'Available',
    price: 50,
    registered: '2024-04-25',
    action: true,
    groupNumber: 3,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 10',
    id: '010',
    availability: 'Service',
    price: 55,
    registered: '2024-04-24',
    action: false,
    groupNumber: 3,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 1',
    id: '0011',
    availability: 'Available',
    price: 10,
    registered: '2024-04-20',
    action: true,
    groupNumber: 2,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 2',
    id: '0021',
    availability: 'Booked',
    price: 15,
    registered: '2024-04-18',
    action: false,
    groupNumber: 1,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 3',
    id: '0031',
    availability: 'Available',
    price: 20,
    registered: '2024-04-22',
    action: true,
    groupNumber: 2,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 4',
    id: '0041',
    availability: 'Booked',
    price: 25,
    registered: '2024-04-16',
    action: false,
    groupNumber: 3,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 5',
    id: '0051',
    availability: 'Available',
    price: 30,
    registered: '2024-04-19',
    action: true,
    groupNumber: 4,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 6',
    id: '0061',
    availability: 'Service',
    price: 35,
    registered: '2024-04-21',
    action: false,
    groupNumber: 1,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 7',
    id: '0071',
    availability: 'Service',
    price: 40,
    registered: '2024-04-23',
    action: true,
    groupNumber: 2,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 8',
    id: '0081',
    availability: 'Booked',
    price: 45,
    registered: '2024-04-17',
    action: false,
    groupNumber: 2,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 9',
    id: '0091',
    availability: 'Available',
    price: 50,
    registered: '2024-04-25',
    action: true,
    groupNumber: 2,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
  {
    name: 'Item 10',
    id: '0101',
    availability: 'Service',
    price: 55,
    registered: '2024-04-24',
    action: false,
    groupNumber: 3,
    description:
      'A surfboard is a specialized piece of equipment used in the sport of surfing. Designed to be buoyant yet maneuverable, surfboards are crafted in various shapes and sizes to accommodate different surfing s, wave conditions, and rider preferences. The construction typically involves materials such as foam, fiberglass, and epoxy to provide a balance between strength and lightness. Key components of a surfboard include the nose (front), tail (back), rails (edges), and fins, which aid in stability.',
    material: 'Plastic',
    type: 'Surf board',
    unitMeasurement: 'cm',
    length: 173,
    width: 50,
    thickness: 20,
    volume: 173,
    tailShape: 'Square',
    noseShape: 'Pointed',
    rails: 'Soft',
    rocker: 'High nose rocker',
    rentedAmount: 11,
    rentedTime: '2 hours 22 minutes',
    rank: 34,
    totalRanks: 1432,
    qrCode: 'https://www.npmjs.com/package/qrCodecode.react',
  },
];

const Table: FC<TableProps> = () => {
  const { t } = useTranslation();

  return (
    <div className={s.container}>
      <table className={s.table}>
        <tbody>
          <tr className={s.header}>
            <th></th>
            <th className={s.name}>{t('Inventory.Equipment name')}</th>
            <th className={s.qr}>{t('Inventory.QR')}</th>
            <th className={s.id}>{t('Inventory.ID')}</th>
            <th className={s.availability}>{t('Inventory.Availability')} </th>
            <th className={s.price}>{t('Inventory.Price')}</th>
            <th className={s.reg}>{t('Inventory.Registered')}</th>
            <th className={s.action}>{t('Inventory.Action')}</th>
          </tr>
          {inventory.map(item => (
            <TableRow key={item.id} item={item} />
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default Table;
